name: Build EXE on Windows

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: チェックアウト
      uses: actions/checkout@v3

    - name: Pythonセットアップ
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: ライブラリインストール
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: EXEビルド
      run: |
        pyinstaller seathr.py --onefile --clean

    - name: アップロード
      uses: actions/upload-artifact@v4
      with:
        name: seathr-exe
        path: dist/seathr.exe
